# Generated by Django 3.2 on 2023-01-25 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0005_alter_hadith_text_image_verifier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith_text_image',
            name='analyst_id',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'Analyst'}, on_delete=django.db.models.deletion.CASCADE, related_name='Analyst', to='VSapp.userinformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hadith_text_image',
            name='verifier_id',
            field=models.ForeignKey(limit_choices_to={'role': 'Verifier'}, on_delete=django.db.models.deletion.CASCADE, related_name='Verifier', to='VSapp.userinformation'),
        ),
    ]
