# Generated by Django 3.2 on 2023-01-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0006_auto_20230126_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith_text_image',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
