# Generated by Django 3.2 on 2023-01-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0007_hadith_text_image_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith_text_image',
            name='analyzed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hadith_text_image',
            name='verifier_date',
            field=models.DateField(null=True),
        ),
    ]
