# Generated by Django 3.2 on 2023-01-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0008_auto_20230126_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith_text_image',
            name='analyst_id',
            field=models.ForeignKey(limit_choices_to={'role': 'Analyst'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Analyst', to='VSapp.userinformation'),
        ),
        migrations.AlterField(
            model_name='hadith_text_image',
            name='verifier_id',
            field=models.ForeignKey(limit_choices_to={'role': 'Verifier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verifier', to='VSapp.userinformation'),
        ),
    ]
