# Generated by Django 3.2 on 2023-01-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0009_auto_20230126_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadith_text_image',
            name='status',
        ),
        migrations.AddField(
            model_name='hadith_text_image',
            name='analyzation_status',
            field=models.CharField(choices=[('Not Analyzed', 'Not Analyzed'), ('Analyzed', 'Analyzed'), ('Wrong', 'Wrong')], default='Not Analyzed', max_length=30),
        ),
        migrations.AddField(
            model_name='hadith_text_image',
            name='verification_status',
            field=models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Wrong', 'Wrong')], default='Not Verified', max_length=30),
        ),
    ]
