# Generated by Django 3.2 on 2023-05-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0013_remove_hadith_text_image_analyzed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgSaveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('image_files', models.FileField(max_length=254, upload_to='image_files')),
            ],
        ),
    ]
