# Generated by Django 3.2 on 2023-05-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0014_imgsavefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgsavefile',
            old_name='image_files',
            new_name='image_file',
        ),
    ]
