# Generated by Django 3.2 on 2023-07-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0015_rename_image_files_imgsavefile_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith_text_image',
            name='englist_translation',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='hadith_text_image',
            name='urdu_translation',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
