# Generated by Django 3.2 on 2023-08-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0016_auto_20230801_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hadith_text_image',
            old_name='verifier_date',
            new_name='hadith_due_date',
        ),
        migrations.AddField(
            model_name='hadith_text_image',
            name='hadith_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Wrong', 'Wrong'), ('Pending', 'Pending')], default='Pending', max_length=35),
        ),
        migrations.AddField(
            model_name='hadith_text_image',
            name='reviewer_id',
            field=models.ForeignKey(limit_choices_to={'role': 'Reviewer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer', to='VSapp.userinformation'),
        ),
        migrations.AlterField(
            model_name='hadith_text_image',
            name='verification_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Wrong', 'Wrong')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Verifier', 'Verifier'), ('Reviewer', 'Reviewer')], default='USER', max_length=20),
        ),
    ]
