# Generated by Django 3.2 on 2023-08-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0017_auto_20230802_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith_text_image',
            name='verification_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Wrong', 'Wrong'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
    ]
