# Generated by Django 3.2 on 2023-08-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0018_alter_hadith_text_image_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith_text_image',
            name='hadith_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Wrong', 'Wrong'), ('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=35),
        ),
    ]
