# Generated by Django 3.2 on 2023-08-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0019_alter_hadith_text_image_hadith_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=1000000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hadith_text_image',
            name='book_id',
            field=models.IntegerField(default=0, max_length=10000000),
        ),
    ]
