# Generated by Django 3.2 on 2023-08-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0021_alter_hadith_text_image_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='book_files',
            field=models.FileField(default=None, max_length=200000, upload_to='Book PDF'),
            preserve_default=False,
        ),
    ]
