# Generated by Django 3.2 on 2023-08-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0022_book_table_book_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith_text_image',
            name='book_id',
            field=models.CharField(default='0', max_length=254),
        ),
    ]
