# Generated by Django 3.2 on 2023-08-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0023_alter_hadith_text_image_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='book_files',
            field=models.FileField(max_length=200000, upload_to='Book_PDF'),
        ),
    ]
