# Generated by Django 3.2 on 2023-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSapp', '0024_alter_book_table_book_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith_text_image',
            name='url',
            field=models.CharField(max_length=100000000000, null=True),
        ),
    ]
